#!/usr/bin/env node
// Fail a production build when the paper index is absent (IMP-028).
//
// `vite build` copies `public/**` verbatim, and only if that directory already
// exists. A fresh checkout has no `public/data` -- it is gitignored, because the
// index is generated by `scripts/build_index.py` -- so a build without one exits
// 0, produces a `dist` with no `dist/data` at all, and deploys a site that reads
// "No paper index yet" forever. Nothing downstream notices: the JS and CSS
// content hashes are byte-identical either way, because the index is copied in
// as files and never inlined, and `GET /data/index.json` still answers 200 from
// the single-page-app fallback, so an HTTP health check cannot see the
// difference. This guard is what makes the build fail closed instead.
//
// It runs from the `build` script alone, before `vite build`, so `npm run dev`
// and `npm test` never invoke it: a missing index costs a developer nothing
// until they are trying to produce something deployable. Both of those also run
// on CI, and neither may start failing because of this.
//
// Written as plain Node ESM rather than a Vite plugin so that the exact code
// the build runs can be pointed at any directory and exercised directly, and so
// that a config-file change cannot silently stop gating. It is outside the
// TypeScript project (`tsconfig.json` includes `src` and `vite.config.ts` only),
// so `npm run typecheck` is unaffected.

import { existsSync, readFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const DEFAULT_DATA_DIR = "public/data";

function fail(lines) {
  for (const line of lines) {
    process.stderr.write(`${line}\n`);
  }
  process.exit(1);
}

// The path as the developer would type it, so the message names the file the
// same way the build script and the readme do rather than as an absolute path.
function displayPath(target) {
  return relative(process.cwd(), target) || ".";
}

function readManifest(manifestPath) {
  const named = displayPath(manifestPath);
  if (!existsSync(manifestPath)) {
    fail([
      `No paper index to build against: ${named} does not exist.`,
      "",
      "A production build has to ship the paper index, and `vite build` copies",
      "public/data verbatim only when that directory is already there -- so this",
      "build would succeed and produce a dist with no dist/data, and the",
      'deployed site would read "No paper index yet" forever. A 200 from',
      "GET /data/index.json would not reveal it: the single-page-app fallback",
      "answers for any missing path.",
      "",
      "Generate the index first, from the repository root:",
      "    python scripts/build_index.py",
      "",
      `To check a directory other than ${DEFAULT_DATA_DIR}, pass it as the one`,
      "argument:",
      "    node scripts/require-index.mjs <dir>",
    ]);
  }
  try {
    return { manifest: JSON.parse(readFileSync(manifestPath, "utf8")), named };
  } catch (error) {
    fail([`${named} could not be read as an index manifest: ${error.message}`]);
  }
  return null;
}

function checkShardFiles(dataDir, manifest, named) {
  if (!Array.isArray(manifest.shards)) {
    fail([`${named} has no "shards" list, so it is not an index manifest.`]);
  }
  if (manifest.shards.length === 0) {
    fail([
      `${named} names no shards, so there is no index to ship.`,
      "",
      "An index with an empty shards list is what a run that collected no",
      "papers writes, and the site renders it as an empty feed rather than as a",
      "missing index, which makes the failure quieter, not louder.",
    ]);
  }
  for (const shard of manifest.shards) {
    const name = shard === null || shard === undefined ? undefined : shard.file;
    if (typeof name !== "string" || name === "") {
      fail([`${named} has a shard entry without a "file" name.`]);
    }
    if (!existsSync(join(dataDir, name))) {
      fail([
        `The paper index at ${named} names a shard that is not there: ${name}`,
        "",
        "build_index.py writes the shards before the manifest, so a manifest",
        "referring to a missing shard means the index was assembled by hand or",
        "partly copied. Shipping it gives the site an index that cannot load.",
      ]);
    }
  }
}

function main(argv) {
  const dataDir = resolve(argv[0] ?? DEFAULT_DATA_DIR);
  const { manifest, named } = readManifest(join(dataDir, "index.json"));
  checkShardFiles(dataDir, manifest, named);
  process.stdout.write(
    `Paper index present: ${named} with ${manifest.shards.length} shard(s).\n`,
  );
}

main(process.argv.slice(2));
