#!/usr/bin/env python3
"""Generate the pinned fixture indices IMP-225 measures against.

Why this exists
---------------
`.improve/artifacts/baseline/baseline-feed-preview-build-desktop-1280.png`
(the 13 baselines captured on Oct 1) renders the hero line

    2,812 papers from cs.CV, cs.LG, cs.CL, cs.AI, cs.RO - index generated Oct 1, 2026

while the index served today renders

    14,253 papers ... index generated Oct 3, 2026

`web/public/data/` is in `.gitignore` and is regenerated by a scheduled
GitHub Action, so the feed is a function of a dataset that changes on its own
schedule. That is data drift, and it is unbounded in time. This script builds
*fixed* indices so a capture can be pinned to a dataset that cannot move.

Four fixtures, all derived from the real index read at run time (so the
structure always matches what the app actually consumes) and all written with
sorted keys and a fixed separator so the bytes are reproducible:

  mirror    identical manifest and identical paper records -> the pin itself.
            Comparing two independently generated mirrors is the only honest
            test of "does this harness render the same bytes twice".
  shifted   same manifest shape and same paper count, but every title/author/
            abstract replaced by a deterministic function of the paper id and
            every `published` moved back seven days -> models "the same week of
            arXiv, one week later". diff(mirror, shifted) is the pure
            data-drift cost with zero rendering nondeterminism in it.
  asof-oct1 filtered to `published <= 2026-10-01` and truncated to the newest
            2,812 papers, with the manifest rewritten to match -> reconstructs
            the dataset the Oct-1 baselines were captured against, to the
            extent that the current shards can express it.
  thin      5 papers in 1 shard -> the smallest dataset that still renders a
            feed, for checking that nothing in the harness depends on volume.

Usage:
  python3 gen_fixture.py --real /tmp/imp225/dist/data --out .improve/tools/imp225/fixture [names...]
"""
import argparse
import hashlib
import json
import os
import shutil

CATS = ["cs.CV", "cs.LG", "cs.CL", "cs.AI", "cs.RO"]

WORDS = (
    "adaptive robust latent spectral sparse equivariant hierarchical "
    "calibrated federated contrastive recurrent compositional invariant "
    "distributional stochastic proximal anisotropic differentiable "
    "topological probabilistic amortised convolutional variational "
    "self-supervised disentangled non-parametric"
).split()


def det_title(pid: str, salt: str) -> str:
    """Deterministic, obviously-synthetic title derived from the paper id.

    Deterministic on purpose: the whole point is that no clock, no RNG seed
    and no network is consulted, so two runs on two machines produce the same
    fixture bytes.
    """
    h = hashlib.sha256((salt + pid).encode()).digest()
    n = 4 + h[0] % 4
    words = [WORDS[(h[i + 1] + i * 7) % len(WORDS)] for i in range(n)]
    tail = ["Retrieval", "Estimation", "Inference", "Generation", "Alignment"][
        h[0] % 5
    ]
    return f"{tail} with {words[0]} {words[1]} representations ({pid})"


def det_authors(pid: str, salt: str) -> list:
    h = hashlib.sha256(("a" + salt + pid).encode()).digest()
    out = []
    for i in range(1 + h[0] % 3):
        given = ["Ada", "Bo", "Cai", "Dara", "Eli", "Fen", "Gus", "Hana"][h[i + 1] % 8]
        family = [
            "Alvarez",
            "Bianchi",
            "Costa",
            "Dubois",
            "Eriksen",
            "Farah",
            "Gupta",
            "Haddad",
        ][h[i + 5] % 8]
        out.append(f"{given} {family}")
    return out


def det_abstract(pid: str, salt: str) -> str:
    h = hashlib.sha256(("x" + salt + pid).encode()).digest()
    base = (
        f"Fixture abstract for {pid}. "
        "This record is generated by .improve/tools/imp225/gen_fixture.py and "
        "is not a real arXiv paper. "
    )
    tail = " ".join(WORDS[(h[i] + i * 3) % len(WORDS)] for i in range(14))
    return (base + tail).strip()


def load_real(real_dir):
    manifest = json.load(open(os.path.join(real_dir, "index.json")))
    shards = {}
    for s in manifest["shards"]:
        d = json.load(open(os.path.join(real_dir, s["file"])))
        shards[s["file"]] = d
    return manifest, shards


def write(out_dir, name, manifest, shards):
    d = os.path.join(out_dir, name)
    os.makedirs(d, exist_ok=True)
    for f in os.listdir(d):
        os.remove(os.path.join(d, f))
    with open(os.path.join(d, "index.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, sort_keys=True, ensure_ascii=False)
        fh.write("\n")
    for fname, shard in shards.items():
        with open(os.path.join(d, fname), "w", encoding="utf-8") as fh:
            json.dump(shard, fh, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return d


def rebuild_manifest(manifest, shards):
    m = json.loads(json.dumps(manifest))
    m["shards"] = [
        {
            "week": s["week"],
            "from": s.get("from"),
            "to": s.get("to"),
            "count": len(shards[s["file"]]["papers"]),
            "file": s["file"],
        }
        for s in manifest["shards"]
    ]
    m["totalPapers"] = sum(e["count"] for e in m["shards"])
    return m


def make_mirror(real_dir, out_dir):
    manifest, shards = load_real(real_dir)
    m = rebuild_manifest(manifest, shards)
    return write(out_dir, "mirror", m, shards)


def make_shifted(real_dir, out_dir):
    manifest, shards = load_real(real_dir)
    new = {}
    for fname, shard in shards.items():
        papers = []
        for p in shard["papers"]:
            q = dict(p)
            q["title"] = det_title(p["id"], "imp225-shift")
            q["authors"] = det_authors(p["id"], "imp225-shift")
            q["abstract"] = det_abstract(p["id"], "imp225-shift")
            q["published"] = shift_day(p["published"], -7)
            q["updated"] = shift_day(p.get("updated") or p["published"], -7)
            papers.append(q)
        new[fname] = {"week": shard["week"], "from": shard.get("from"), "to": shard.get("to"), "papers": papers}
    m = rebuild_manifest(manifest, new)
    m["categories"] = CATS
    return write(out_dir, "shifted", m, new)


def make_asof_oct1(real_dir, out_dir, cap=2812):
    """Newest `cap` papers with published <= 2026-10-01, redistributed over the
    manifest's own weeks so week boundaries stay truthful."""
    manifest, shards = load_real(real_dir)
    pool = []
    for fname, shard in shards.items():
        for p in shard["papers"]:
            if p["published"] <= "2026-10-01":
                pool.append((p["published"], p["id"], fname, p))
    pool.sort(key=lambda t: (t[0], t[1]), reverse=True)
    pool = pool[:cap]
    new = {}
    for fname, shard in shards.items():
        new[fname] = {"week": shard["week"], "from": shard.get("from"), "to": shard.get("to"), "papers": []}
    for _pub, _pid, fname, p in pool:
        new[fname]["papers"].append(p)
    for fname in new:
        new[fname]["papers"].sort(key=lambda p: (p["published"], p["id"]), reverse=True)
    m = rebuild_manifest(manifest, new)
    m["generatedAt"] = "2026-10-01T22:55:00Z"
    m["categories"] = CATS
    return write(out_dir, "asof-oct1", m, new)


def make_thin(real_dir, out_dir):
    manifest, shards = load_real(real_dir)
    first = manifest["shards"][0]
    papers = []
    for i in range(5):
        p = dict(shards[first["file"]]["papers"][i])
        p["id"] = f"2601.0000{i}"
        papers.append(p)
    shard = {"week": first["week"], "from": first.get("from"), "to": first.get("to"), "papers": papers}
    m = {
        "generatedAt": "2026-10-03T10:02:17Z",
        "retentionDays": manifest.get("retentionDays", 30),
        "categories": CATS,
        "totalPapers": len(papers),
        "shards": [
            {
                "week": first["week"],
                "from": first.get("from"),
                "to": first.get("to"),
                "count": len(papers),
                "file": "papers-fixture-thin.json",
            }
        ],
    }
    return write(out_dir, "thin", m, {"papers-fixture-thin.json": shard})


def make_pinned(real_dir, out_dir, weeks=2, per_week=30):
    """The fixture a future verifier should pin captures to.

    Fully synthetic: no real arXiv record is copied, so it is ~40 KB and can
    live in git instead of being regenerated from a dataset that moves. Two
    shards so the week/`from`/`to` machinery is exercised, 30 papers each so
    the default 50-card feed and the "Load more" path both have something to
    show, and every field is a pure function of the index number so the bytes
    are identical on every machine and every run.
    """
    shards = {}
    entries = []
    for w in range(weeks):
        fname = f"papers-fixture-w{w}.json"
        # Week `w` sits `7*(weeks-1-w)` days before the pinned reference date
        # 2026-10-01, which is also the newest shard's `to` and therefore the
        # date the app treats as "today" (latestIndexDate).
        to = shift_day("2026-10-01", -7 * (weeks - 1 - w))
        frm = shift_day(to, -6)
        papers = []
        for i in range(per_week):
            pid = f"2601.{w:02d}{i:04d}"
            papers.append(
                {
                    "id": pid,
                    "title": det_title(pid, "imp225-pin"),
                    "authors": det_authors(pid, "imp225-pin"),
                    "abstract": det_abstract(pid, "imp225-pin"),
                    "abstractTruncated": True,
                    "published": shift_day(to, -(i % 7)),
                    "updated": shift_day(to, -(i % 7)),
                    "categories": [CATS[(i + w) % len(CATS)]],
                    "primaryCategory": CATS[(i + w) % len(CATS)],
                    "absUrl": f"http://arxiv.org/abs/{pid}v1",
                    "pdfUrl": f"https://arxiv.org/pdf/{pid}v1",
                    "comment": None,
                    "journalRef": None,
                }
            )
        shards[fname] = {"week": f"2026-W{40 - w}", "from": frm, "to": to, "papers": papers}
        entries.append(
            {
                "week": f"2026-W{40 - w}",
                "from": frm,
                "to": to,
                "count": len(papers),
                "file": fname,
            }
        )
    m = {
        "generatedAt": "2026-10-03T10:02:17Z",
        "retentionDays": 30,
        "categories": CATS,
        "totalPapers": sum(e["count"] for e in entries),
        "shards": entries,
    }
    return write(out_dir, "pinned", m, shards)


def shift_day(iso, days):
    import datetime

    d = datetime.date.fromisoformat(iso)
    return (d + datetime.timedelta(days=days)).isoformat()


BUILDERS = {
    "pinned": make_pinned,
    "mirror": make_mirror,
    "shifted": make_shifted,
    "asof-oct1": make_asof_oct1,
    "thin": make_thin,
}

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--real", default="/tmp/imp225/dist/data")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "fixture"))
    ap.add_argument("names", nargs="*", default=list(BUILDERS))
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    for name in a.names:
        d = BUILDERS[name](a.real, a.out)
        m = json.load(open(os.path.join(d, "index.json")))
        n = sum(s["count"] for s in m["shards"])
        print(f"{name:10s} -> {d}  shards={len(m['shards'])}  papers={n}")